deployments:
  deploymentGating:
    enabled: true 
    retry: 200  
    sleep: 15 
    environments: 
    - prod
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS9kMGRhNzc1MC00OWI2LTExZWYtOWExNi0wYWJlM2Y0YTY2MDE=
