deployments:
  deploymentGating:
    enabled: true 
    retry: 200  
    sleep: 15 
    environments: 
    - prod
  services:
    ids:
    - ari:cloud:graph::service/203ed1a4-142a-414c-ab68-058c300d8011/d0da7750-49b6-11ef-9a16-0abe3f4a6601
